# Generated by Django 3.2.5 on 2021-11-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('m', 'M'), ('l', 'L'), ('XL', 'XL'), ('X', 'X')], default=('M', 'M'), max_length=200),
        ),
    ]
